name: Frontend Project

on:
  push:
    paths:
      - "frontend/**"
    branches:
      - main
  pull_request:
    paths:
      - "frontend/**"
    branches:
      - main

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          dir: "frontend"
          cmd: install

      - name: Run lint in sub-folder
        uses: borales/actions-yarn@v4
        with:
          cmd: lint
          dir: "frontend"

      - name: Run prettier in sub-folder
        uses: borales/actions-yarn@v4
        with:
          cmd: prettier
          dir: "frontend"

      - name: Run test in sub-folder
        uses: borales/actions-yarn@v4
        with:
          cmd: test
          dir: "frontend"

env:
  PORT: ${{ secrets.PORT }}
  API_URL: ${{ secrets.API_URL }}
